### PR TITLE
Merge from alphagov

### PR DESCRIPTION
**Pull request by Floppy**
Replaces #10, with problems resolved. Still WIP though.

### CODE REVIEW

**Comment by pezholio** [comment]
@Floppy Is this the current state of play, or are there any more commits to push up?

**Comment by Floppy** [comment]
This is WIP for https://github.com/theodi/shared/issues/613

**Comment by Floppy** [comment]
Current state: a few tests failing due to some sort of change in slash-encoding in URLs.

**Comment by pezholio** [comment]
Boom - and we have green. I'm going to push this up to Heroku and see where we are

**Comment by pezholio** [comment]
This is now ready to go, and will deploy to Heroku. Moiging.

**Pull request merged**
